### ISSUE TITLE
ENV Files Need Consolidating and Refactoring

### ISSUE THREAD

**Issue by martinpeck** [microsoft/AzureTRE#1470]
We have too many .env files, and pretty much everything in the `Makefile` needs values from both/all.

We need to revisit this in order to streamline dev setup.

A full review of the two .env files, plus what's actually needed for debugging locally, should take place.

**Comment by marrobi** [comment]
The reason for a separate .env file for the core TRE deployment, to the devops/bootstrap, was that will likely have multiple TRE environments, hence TRE_IDs, sharing the same ACR etc.

From a GitHub actions perspective its repository secrets vs environment secrets.

Agree needs some thought.

**Comment by LizaShak** [comment]
Tasks to complete the story:

1. Have one config file at root (remove the previous ones)
2. Consider what should be  the config file format:  yml/json...
3. Auth setup updates the new config file
4. Making sure all make commands are working
5. Decide how should we handle the private.env?  Make sure the local debugging works.
6. Consider all the .env.sample files, how are we handling them? for example: /workspaces/AzureTRE/templates/workspaces/base/.env.sample
7. Update the Deployment Repo  
8. Update documentation

@martinpeck @marrobi @tamirkamara WDYT? Anything you would like add?

**Comment by tamirkamara** [comment]
Another item we might want to include is how to migrate existing settings to the new file.

**Comment by martinpeck** [comment]
Out of JSON and YAML, I'd probably suggest that YAML is the better one given that these files will be edited by humans.

That said, have we considered TOML as the format?

It's closer to what we have (name/value pairs), while allowing us to have a little more structure. 

Also, it's very easily loaded in our Python code (via https://pypi.org/project/tomli/)

Just a thought. Please ignore it if you feel

**Comment by martinpeck** [comment]
Out of interest, why are we considering YAML/JSON etc? Is that because it's easier to parse programatically, or because it allows us to add structure?

At the end of the day, we still "flattern" these files into environment variables. I assume any additional structure/hierarchy will, presumably, get lost once we export the name/value pairs as environment variables.

So, if the change of format is...

1. to make things more readable
2. to better group/structure the values

... but, we're still expecting them to be edited by hand, then we want to make reading/editing as easy as possible and as error free as possible, even if that makes parsing/processing the files a little harder for us. For me, that makes TOML a slightly better choice as it's easy to read, easy to edit, and probably quite easy to migrate from .env files.

**Comment by LizaShak** [comment]
@martinpec

I think at this point we have quite a lot of configuration, it would be good to group and organize settings (hierarchical) to make it more readable. Another requirement would be that we are able to validate it ahead  and support basic types. 

 Therefore I think the ini and TOML formats are less relevant for us, since they are not hierarchical. They also quite verbose and not obvious to use.(For example, the [[syntax]] representing an array). These formats are recommended when you don't have a lot of configuration but I think we do and it comes out quite long and hard to read.c

Considered also to use Json - but it doesn't allow to add comments. Since we ask customers to fill those config files, comments and guidance is important in our case.  
Therefore I think a good format for us would be yaml. 

WDYT?

**Comment by LizaShak** [comment]
also read that for TOML different parsers will operate in subtly different ways that can lead to often obscure edge case bugs regarding the way whitespace is used, case sensitivity, comments and escape characters.

**Comment by LizaShak** [comment]
Not a lot of hierarchy, but at this point it is good to have it. Adding here an example for TOML env file: https://github.com/gazreese/gazreese.com/blob/c4c3fa7d576a4c316f11f0f7a652ca11ab23586d/Hugo/config.toml (also showing the double brackets I meant). I think people are more familiar with yaml, TOML it is too verbose and less clean in my opinion.

**Comment by martinpeck** [comment]
Ah....lists of "objects". Got it.

I agree...the primary contributors to this project are probably more familiar with YAML, and we already have instance of YAML files in our repo, and we probably have YAML extensions for VS Code enabled too. For these reasons alone it probably wins. If we were using `project.toml` files for our Python project or for our tests then that might be different.

I'm not sure I agree that TOML is more verbose (compared to YAML). I also think that YAML might allow us/encourage us to add more complexity to our config than we need.

I still think we should throw together an example of what the end-state might look like before we go ahead and change all the ENV files to YAML. It would be good to see an example of the final YAML file we're aiming for before we convert all of our code/scripts.

**Comment by LizaShak** [comment]
Here is my suggestion for the config.yml file (I'd be happy to hear your thoughts/additions/changes):

```yml
# After you have replaced all the __CHANGE_ME__ values in this file, you need to
# run `make auth` to setup the Auth.

management:
  location: __CHANGE_ME__
  mgmt_resource_group_name: __CHANGE_ME__
  mgmt_storage_account_name: __CHANGE_ME__
  terraform_state_container_name: tfstate
  acr_name: __CHANGE_ME__
  # Azure Resource Manager credentials used for CI/CD pipelines
  arm_subscription_id: __CHANGE_ME__

  # If you want to override the currently signed in credentials
  # You would do this if running commands like `make terraform-install DIR=./templates/workspaces/base`
  # arm_tenant_id: __CHANGE_ME__
  # arm_client_id: __CHANGE_ME__
  # arm_client_secret: __CHANGE_ME__

tre:
  tre_id: "__CHANGE_ME__"
  # If your local machine/build agent cannot get the public IP
  # address from https://ipecho.net/plain, then you can circumvent
  # this by setting this Environment variable. This blockage can
  # be caused by trying to deploy TRE in an Office environment where
  # this website is blocked. This value is the public facing IP
  # address of the deploying machine.
  # public_deployment_ip_address: __CHANGE_ME__
  defaults:
    core_address_space: "10.1.0.0/22"
    tre_address_space: "10.0.0.0/12"

    core_app_service_plan_sku: "P1v2"
    resource_processor_vmss_sku: "Standard_B2s"
    enable_airlock_malware_scanning: false

    # TODO: move to RP default with https://github.com/microsoft/AzureTRE/pull/2634
    workspace_app_service_plan_sku: "P1v2"
    # Uncomment to disable the UI provided as part of this repo
    # deploy_ui: false

resource_processor:
    # The number of processes to start in the resource processor VMSS image
    # resource_processor_number_processes_per_instance: 5

    # This setting provides a way to pass environment values to the resource processor to use as a source of bundle parameter values
    # For example, to specify your image_gallery_id for use in VM user resources with custom VM images:
    # rp_bundle_values: {"image_gallery_id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/<your-rg>/providers/Microsoft.Compute/galleries/<your-gallery-name>"}


authentication:
  aad_tenant_id: "__CHANGE_ME__"
  # Setting AUTO_WORKSPACE_APP_REGISTRATION to false will create an identity with `Application.ReadWrite.OwnedBy`.
  # Setting AUTO_WORKSPACE_APP_REGISTRATION to true will create an identity with `Application.ReadWrite.All` and `Directory.Read.All`.
  # When this is true, create Workspaces will also create an AAD Application automatically.
  # When this is false, the AAD Application will need creating manually.
  auto_workspace_app_registration: true
  # Setting AUTO_WORKSPACE_GROUP_CREATION to true will create an identity with `Group.ReadWrite.All`
  auto_workspace_group_creation: false

developer_settings:
  # Locks will not be added to stateful resources so they can be easily removed
  # stateful_resources_locked: false

  # If you want to use TRE_URL to point to your local TRE API instance,
  # uncomment and set this variable
  # tre_url: __CHANGE_ME__

  # This setting will enable your local machine to be able to
  # communicate with Service Bus and Cosmos. It will also allow deploying
  # the base workspace.
  # enable_local_debugging: true

  # Used by the API and Resource processor application to change log level
  # debug: true
```
