### ISSUE TITLE
Base workspace template is broken due to running TF in the upgrade action

### ISSUE THREAD

**Issue by tamirkamara** [microsoft/AzureTRE#2114]
**Describe the bug**
As long as we don't have a solution for secrets in subsequent runs of Terraform we can't run it in the bundle's upgrade action.
Running an upgrade will cause any secret to be reset to the REDACTED string (or anything else persisted by the API) which isn't the desired behavior.

**Comment by tamirkamara** [comment]
Closing this one as mitigated. Will open another issue to re-enable TF to run in the upgrade action.

**Comment by marrobi** [comment]
@tamirkamara in the base workspace porter it says:

```
  - exec:
      description: "Update workspace app redirect urls"
      command: ./update_redirect_urls.sh
      flags:
        workspace-api-client-id: "{{ bundle.parameters.client_id }}"
        aad-redirect-uris-b64: "{{ bundle.parameters.aad_redirect_uris }}"
        # always update with the script since we don't run TF for upgrade
        # might need to change when https://github.com/microsoft/AzureTRE/issues/2114 is resolved.
        register-aad-application: "false"
        # register-aad-application: "{{ bundle.parameters.register_aad_application }}"
        
```

Did an issue get created to revert this?
