### ISSUE TITLE
[Task] Implement publish_workspace.sh script

### ISSUE THREAD

**Issue by deniscep** [microsoft/AzureTRE#219]
Story: #138

Change the publish_vanilla_workspace.sh:
- [x] to be generic publish_workspace.sh: takes in parameter for workspace (e.g. vanilla workspace). (Part of makefile)
- [x] registers workspace using the API POST to /workspace-templates

**Comment by marrobi** [comment]
Looking at the porter `bundle.json`, the parameter definitions do not follow JSON schema standard.

I don't believe we should be be importing properties in a porter specific format as we will need code to translate these and do custom validation.

Unless somebody can enlighten me as to translating the porter bundle parameters and definitions to JSON Schema, I expect we will need a separate schema document.

**Comment by marrobi** [comment]
Ok,  as far as embedding schema in the porter bundle, I couldn't get custom values to display as an output of `porter explain`

**What did work:**

Add a `schema.json` as part of the bundle. And a custom action:

```
customActions:
  json_schema:
    description: "Get JSON Schema"
    stateless: true
    modifies: false

json_schema:
  - exec:
      description: "Get JSON Schema"
      command: cat
      arguments:
        - schema.json"
```

Then run:

```
$ porter invoke --action jsonSchema -p ./parameters.json --cred ./azure.json
invoking tre-service-azureml...
executing jsonSchema action from tre-service-azureml (installation: tre-service-azureml)
Get JSON Schema
{"title": "Workspace", "type": "object", "properties": {"name": {"title": "Name", "type": "string"}, "address_space": {"title": "Address Space", "type": "string", "format": "ipv4network"}}, "required": ["name", "address_space"]}execution completed successfully!
```
We can then parse the schema.

We do need to have parameters set/env vars even if dummy ones. So:

```
export $(grep -v '^#' .env.sample | xargs)
porter invoke --action jsonSchema -p ./parameters.json --cred ./azure.json
```

Thoughts?
