### ISSUE TITLE
Some templates have outputs defined for install but not upgrade

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#3685]
This means:

```
outputs:
  - name: ip
    type: string
    applyTo:
      - install
```
 
will only update on install, if the first deploy fails, and succeed on second attempt/update the fields never appear, so this should be:

```
outputs:
  - name: ip
    type: string
    applyTo:
      - install
      - upgrade  
```      

and should be listed under:

```
upgrade:
  - terraform:
     - outputs:
```

All `porter.yaml` files should be updated.

**Comment by Sweetdevil144** [comment]
Hello @marrobi . I would like to take up this issue. Also, I would like to know more about this in detail.

**Comment by marrobi** [comment]
@Sweetdevil144 are you still interested in this? As per the description all bundles should have outputs defined for both install and upgrade.

**Comment by Sweetdevil144** [comment]
Hey @marrobi . If possible, then sure. I would like to tackle this as it would prove beneficial for me too.

**Comment by marrobi** [comment]
I've assigned it to yourself.

**Comment by Sweetdevil144** [comment]
Okay @marrobi . Thanks for assigning me the role. I just want you to comment on the following changes I'm making in one of the porter.yaml template:
```yaml
...

outputs:
  - name: app_role_id_workspace_owner
    type: string
    applyTo:
      - install
      - upgrade
  - name: app_role_id_workspace_researcher
    type: string
    applyTo:
      - install
      - upgrade
  - name: app_role_id_workspace_airlock_manager
    type: string
    applyTo:
      - install
      - upgrade
  - name: client_id
    type: string
    applyTo:
      - install
      - upgrade
  - name: scope_id
    type: string
    applyTo:
      - install
      - upgrade
  - name: sp_id
    type: string
    applyTo:
      - install
      - upgrade

...

upgrade:
  - terraform:
      description: "Upgrade workspace"
      ...
      outputs:
        - name: app_role_id_workspace_owner
        - name: app_role_id_workspace_researcher
        - name: app_role_id_workspace_airlock_manager
        - name: client_id
        - name: scope_id
        - name: sp_id
  ...
```
