### ISSUE TITLE
[Story] Configure Github workflows to allow PRs from forks to be deployed and validated

### ISSUE THREAD

**Issue by marrobi** [microsoft/AzureTRE#478]
## Description

As a  project maintainer
I want to validate an incoming PR from a fork deploys successfully and tests pass.
So that I can merge PRs from external contributors

## Acceptance criteria

- [x] PRs that have been "reviewed" and labelled/commented on by maintainers can deploy via CD and access secrets
- [x] External contributors cannot access secrets or bypass the labelling mechanism.

See https://securitylab.github.com/research/github-actions-preventing-pwn-requests/ and suggest a solution

**Comment by christoferlof** [comment]
Not sure it's a good idea to deploy from forks. We need to run validation on PRs from forks. Lets discuss how to potentially split this into multiple checks/workflows.

**Comment by marrobi** [comment]
I believe we need the ability to spin up a fresh deployment based on a PR from a fork on demand.

**Comment by tompaana** [comment]
Tested a possible solution (from the link in the description):

In a workflow:

```yaml
on:
  pull_request_target:
    types: [labeled]

jobs:
  build:
    ...
    if: github.event.pull_request.head.repo.full_name == github.repository || contains(github.event.pull_request.labels.*.name, 'safe to test')
```

The result: PRs created from a branch of the source repository run the workflow as usual. PRs coming from forks require the custom label, "safe to test" in this case, to run the workflow - it will be in "skipped" state until the label is added.
